compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.9.3.cjs
