sonar.projectKey=ccd-case-print-service
sonar.language=ts
sonar.sources=src/main/
sonar.tests=src/test/
sonar.exclusions=node_modules/**,coverage/**,src/main/public/**,src/main/resources/**,src/main/views/**,src/main/**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/app-insights/**,src/main/app.ts,src/main/server.ts,src/main/router/**,src/main/util/**,src/main/modules/**,src/main/public/**,src/main/resources/**,src/main/views/**,src/main/**/*.spec.ts
