nodejs:
  aadIdentityName: ccd
  image: 'hmctspublic.azurecr.io/ccd/case-print-service:latest'
  ingressHost: return-case-doc-ccd.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 3100
  cpuLimits: 1
  memoryRequests: '512Mi'
  cpuRequests: '250m'
  memoryLimits: '2048Mi'
  autoscaling:
    enabled: false
    maxReplicas: 4
  environment:
    # Node specific vars
    USE_CSRF_PROTECTION: true
    SECURITY_REFERRER_POLICY: origin
    HPKP_MAX_AGE: 2592000
    HPKP_SHA256S: Set-proper-SHA256s
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    NODE_CONFIG_DIR: ./config
    TS_BASE_URL: ./src/main
    CASE_DATA_STORE_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_DATA_PROBATE_TEMPLATE_URL: http://probate-back-office-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    # Logging vars
    REFORM_TEAM: ccd
    REFORM_SERVICE_NAME: case-print-service
    REFORM_ENVIRONMENT: "{{ .Values.global.environment }}"
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_BASE_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/'
    IDAM_S2S_AUTH: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_SERVICE_NAME: ccd_ps
  keyVaults:
    ccd:
      secrets:
        - microservicekey-ccd-ps
        - AppInsightsInstrumentationKey
