nodejs:
  image: 'hmctspublic.azurecr.io/ccd/case-print-service:latest'
  applicationPort: 3100
  cpuLimits: 1
  environment:
    # Node specific vars
    USE_CSRF_PROTECTION: true
    SECURITY_REFERRER_POLICY: origin
    HPKP_MAX_AGE: 2592000
    HPKP_SHA256S: Set-proper-SHA256s
    NODE_ENV: production
    UV_THREADPOOL_SIZE: 64
    NODE_CONFIG_DIR: ./config
    TS_BASE_URL: ./src/main

    CASE_DATA_PROBATE_TEMPLATE_URL: http://betaDevBprobateApp01.reform.hmcts.net:4104

    # Logging vars
    REFORM_TEAM: ccd
    REFORM_SERVICE_NAME: case-print-service
    REFORM_ENVIRONMENT: aat
    IDAM_SERVICE_NAME: ccd_ps
