vault_section = "preprod"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
probate_template_url = "http://probate-back-office-aat.service.core-compute-aat.internal"
external_host_name = "return-case-doc-ccd.nonprod.platform.hmcts.net"
capacity = "2"
