idam_api_url = "https://idam-api.aat.platform.hmcts.net/"
authentication_web_url = "https://idam-web-public.aat.platform.hmcts.net/"
probate_template_url = "http://probate-sol-ccd-service-demo.service.core-compute-demo.internal"
external_host_name = "return-case-doc.ccd.demo.platform.hmcts.net"
capacity = "2"
