vault_section = "prod"
idam_api_url = "https://prod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://www.idam.reform.hmcts.net"
probate_template_url = "http://probate-back-office-prod.service.core-compute-prod.internal"
external_host_name = "return-case-doc.ccd.platform.hmcts.net"
capacity = "2"
