capacity = "2"
asp_name = "ccd-case-print-service-sprod"
asp_rg = "ccd-case-print-service-sprod"
idam_api_url = "https://idam-api-idam-sprod.service.core-compute-idam-sprod.internal"
authentication_web_url = "https://idam-web-public-idam-sprod.service.core-compute-idam-sprod.internal"
